### ISSUE TITLE
Jenkins error with chrome: Chrome failed to start: exited abnormally   (unknown error: DevToolsActivePort file doesn't exist)

### ISSUE THREAD

**Issue by DB8851** [plotly/pytest-dash#77]
Hey,
I am trying to build my code through Jenkins but below error is encountered, pls help to fix:

unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'stayprime-Lenovo-ideapad-330-15IKB', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.3.0-40-generic', java.version: '11.0.6'
Driver info: driver.version: ChromeDriver
remote stacktrace: #0 0x555af40ca479 <unknown>
-------------------------------------------------------------------------------------------------------------------------
O.S version: Ubuntu 18.04.2 LTS
Chrome version: Version 79.0.3945.88 (Official Build) (64-bit)
Chrome driver version: 79.0.3945.36

**Comment by alexcjohnson** [comment]
`pytest-dash` is no longer maintained - if you're still using it, please transition to `dash.testing`, part of the main `dash` package https://dash.plotly.com/testing

**Comment by DB8851** [comment]
I am not using any pytest-dash. I am using TestNG framework with java.

**Comment by alexcjohnson** [comment]
So why is this posted in the `pytest-dash` repo?  I have never heard of TestNG and cannot help with it.
